// ============================================================================
// Background tile pre-warmer for Indonesian cities.
// ----------------------------------------------------------------------------
// Phase 3 of the tile-resilience layer. Walks a city's bounding box at
// the zoom levels customers actually use (city overview → neighbourhood),
// and fires fetch() for each tile. The Service Worker (Phase 1) catches
// each response and tucks it into the cache, so the next time the user
// opens the app or pans to that area they get instant tiles even with
// zero signal.
//
// COST CONTROL:
//   • Capped at MAX_TILES per call to avoid runaway prefetch
//   • Cooperative concurrency (CONCURRENCY parallel fetches)
//   • Each fetch uses { cache: 'force-cache' } so the browser HTTP cache
//     also short-circuits if it already has the tile
//   • Connection-type aware: skips entirely on save-data / cellular when
//     navigator.connection signals slow links
//
// TILE MATH:
//   For zooms Z = 10..14 over a city bbox:
//     z=10: 1-4 tiles
//     z=11: 4-9 tiles
//     z=12: 16-36 tiles
//     z=13: 64-144 tiles
//     z=14: 256-576 tiles
//   Total per city: 300-700 tiles. A medium city like Yogyakarta is ~450.
//   At 25-50KB per vector tile, that's ~15-25 MB per city — well inside
//   the SW cache budget set in public/sw.js (TILE_LIMIT = 1500).
// ============================================================================

export type CityBbox = {
  slug: string
  name: string
  // [west, south, east, north] in degrees — same convention as MapLibre.
  bbox: [number, number, number, number]
}

// Major Indonesian customer markets, ordered by tourism + B2B priority.
// Bounding boxes are city-administrative footprints (kota/kabupaten),
// roughly +/- 5km around the urban core. Generated by hand from
// OpenStreetMap city relations; not sensitive to small drift.
export const PRELOAD_CITIES: ReadonlyArray<CityBbox> = [
  { slug: 'yogyakarta', name: 'Yogyakarta', bbox: [110.30, -7.85,  110.45, -7.72] },
  { slug: 'denpasar',   name: 'Denpasar',   bbox: [115.18, -8.72,  115.30, -8.60] },
  { slug: 'ubud',       name: 'Ubud',       bbox: [115.24, -8.55,  115.30, -8.48] },
  { slug: 'canggu',     name: 'Canggu',     bbox: [115.13, -8.68,  115.18, -8.62] },
  { slug: 'jakarta',    name: 'Jakarta',    bbox: [106.70, -6.35,  107.00, -6.10] },
  { slug: 'bandung',    name: 'Bandung',    bbox: [107.55, -6.99,  107.72, -6.85] },
  { slug: 'surabaya',   name: 'Surabaya',   bbox: [112.65, -7.35,  112.85, -7.18] },
  { slug: 'malang',     name: 'Malang',     bbox: [112.59, -8.02,  112.69, -7.92] },
  { slug: 'medan',      name: 'Medan',      bbox: [ 98.60,  3.50,   98.75,  3.68] },
  { slug: 'solo',       name: 'Solo',       bbox: [110.78, -7.62,  110.88, -7.53] },
] as const

// Tile providers we mirror — must match the SW's TILE_HOSTS so the cache
// catches them. The first URL is preferred; the SW handles failover.
const TILE_URL_TEMPLATE = 'https://tiles.openfreemap.org/planet/{z}/{x}/{y}.pbf'

// Defaults — tunable per call.
const DEFAULT_ZOOM_MIN = 10
const DEFAULT_ZOOM_MAX = 14
const CONCURRENCY = 6
const MAX_TILES = 1200            // hard cap per call across all zooms
const FETCH_TIMEOUT_MS = 8_000    // skip tiles that hang — we'll get them on demand

function lonToTileX(lon: number, z: number): number {
  return Math.floor(((lon + 180) / 360) * Math.pow(2, z))
}

function latToTileY(lat: number, z: number): number {
  const rad = (lat * Math.PI) / 180
  return Math.floor(
    ((1 - Math.log(Math.tan(rad) + 1 / Math.cos(rad)) / Math.PI) / 2) * Math.pow(2, z),
  )
}

function buildTileUrls(bbox: [number, number, number, number], zmin: number, zmax: number): string[] {
  const [w, s, e, n] = bbox
  const urls: string[] = []
  for (let z = zmin; z <= zmax; z++) {
    const xMin = lonToTileX(w, z)
    const xMax = lonToTileX(e, z)
    // Note: tile Y is inverted (north → smaller Y), so we use n then s.
    const yMin = latToTileY(n, z)
    const yMax = latToTileY(s, z)
    for (let x = Math.min(xMin, xMax); x <= Math.max(xMin, xMax); x++) {
      for (let y = Math.min(yMin, yMax); y <= Math.max(yMin, yMax); y++) {
        urls.push(
          TILE_URL_TEMPLATE
            .replace('{z}', String(z))
            .replace('{x}', String(x))
            .replace('{y}', String(y)),
        )
        if (urls.length >= MAX_TILES) return urls
      }
    }
  }
  return urls
}

type NetworkInformationLike = {
  saveData?: boolean
  effectiveType?: 'slow-2g' | '2g' | '3g' | '4g'
}

function shouldSkipPreload(): boolean {
  if (typeof navigator === 'undefined') return true

  // Skip when PMTiles is the configured tile source — pmtiles serves via
  // HTTP Range requests against a single archive, not XYZ tile fetches,
  // so pre-warming the openfreemap XYZ URLs is pure waste (and floods
  // the dev console with CORS errors since openfreemap doesn't send
  // Access-Control-Allow-Origin). This honours the same env contract
  // resilientStyle.ts uses.
  if (process.env.NEXT_PUBLIC_PMTILES_URL) return true

  // Dev kill switch — silences the openfreemap CORS storm completely.
  if (process.env.NEXT_PUBLIC_MAPS_OFFLINE === 'true') return true

  // Honor Save-Data + slow-link hints. Indonesian users on prepaid plans
  // care more about MB used than instant tiles — respect that signal.
  const conn = (navigator as Navigator & { connection?: NetworkInformationLike }).connection
  if (!conn) return false
  if (conn.saveData) return true
  if (conn.effectiveType === '2g' || conn.effectiveType === 'slow-2g') return true
  return false
}

async function fetchWithTimeout(url: string, timeoutMs: number): Promise<void> {
  if (typeof AbortController === 'undefined') {
    await fetch(url, { cache: 'force-cache', mode: 'cors' }).catch(() => undefined)
    return
  }
  const ctrl = new AbortController()
  const t = setTimeout(() => ctrl.abort(), timeoutMs)
  try {
    await fetch(url, { cache: 'force-cache', mode: 'cors', signal: ctrl.signal })
  } catch {
    /* swallow — pre-warm is best-effort */
  } finally {
    clearTimeout(t)
  }
}

async function runConcurrent(urls: string[], concurrency: number): Promise<void> {
  let idx = 0
  async function worker() {
    while (idx < urls.length) {
      const myIdx = idx++
      await fetchWithTimeout(urls[myIdx], FETCH_TIMEOUT_MS)
    }
  }
  const workers: Promise<void>[] = []
  for (let i = 0; i < Math.min(concurrency, urls.length); i++) {
    workers.push(worker())
  }
  await Promise.all(workers)
}

/**
 * Pre-warm the Service Worker tile cache for a given city's bounding box.
 * Non-blocking — the caller can fire-and-forget. Skips entirely on
 * save-data or 2G connections.
 *
 * @param city  CityBbox to pre-warm (one of PRELOAD_CITIES, or custom)
 * @param opts  Optional zoom range overrides
 * @returns     Number of tiles attempted (0 if skipped)
 */
export async function preloadCityTiles(
  city: CityBbox,
  opts?: { zmin?: number; zmax?: number },
): Promise<number> {
  if (shouldSkipPreload()) return 0
  const zmin = opts?.zmin ?? DEFAULT_ZOOM_MIN
  const zmax = opts?.zmax ?? DEFAULT_ZOOM_MAX
  const urls = buildTileUrls(city.bbox, zmin, zmax)
  await runConcurrent(urls, CONCURRENCY)
  return urls.length
}

/**
 * Pre-warm tiles for an arbitrary bbox — not tied to PRELOAD_CITIES.
 * Used by /cari to warm the actual pickup → dropoff corridor for the
 * user's specific trip, including locations outside our 10 curated
 * cities. Bbox is auto-expanded by ~200m on each side so route
 * pan/zoom outside the strict bounds still hits cached tiles.
 *
 * Returns 0 when skipped (save-data, 2G, PMTiles configured, etc.) or
 * when the bbox is invalid.
 */
export async function preloadBbox(
  bbox: [number, number, number, number],
  opts?: { zmin?: number; zmax?: number; label?: string },
): Promise<number> {
  if (shouldSkipPreload()) return 0
  const [w, s, e, n] = bbox
  if (![w, s, e, n].every((v) => Number.isFinite(v))) return 0
  if (w >= e || s >= n) return 0
  // Pad bbox by ~200m on each side so the user's pinch-out and slight
  // pan after the route loads still hits cached tiles.
  const pad = 0.002 // ~220m at the equator
  const padded: [number, number, number, number] = [w - pad, s - pad, e + pad, n + pad]
  const zmin = opts?.zmin ?? DEFAULT_ZOOM_MIN
  const zmax = opts?.zmax ?? DEFAULT_ZOOM_MAX
  const urls = buildTileUrls(padded, zmin, zmax)
  await runConcurrent(urls, CONCURRENCY)
  return urls.length
}

/**
 * Compute a tight bbox containing both points + an optional buffer
 * (default 5km). Used to derive the warm region for /cari when both
 * pickup + dropoff are set.
 */
export function bboxFromPoints(
  a: { lat: number; lng: number },
  b: { lat: number; lng: number },
  bufferKm = 5,
): [number, number, number, number] {
  const minLat = Math.min(a.lat, b.lat)
  const maxLat = Math.max(a.lat, b.lat)
  const minLng = Math.min(a.lng, b.lng)
  const maxLng = Math.max(a.lng, b.lng)
  const latPad = bufferKm / 111
  // Lng pad shrinks with latitude (away from equator).
  const lngPad = bufferKm / (111 * Math.cos((minLat * Math.PI) / 180))
  return [minLng - lngPad, minLat - latPad, maxLng + lngPad, maxLat + latPad]
}

/**
 * Pick the nearest PRELOAD_CITIES entry to the given lat/lng. Returns
 * undefined if no city centroid is within ~150km (likely the user is
 * outside our primary markets).
 */
export function nearestPreloadCity(lat: number, lng: number): CityBbox | undefined {
  let best: { city: CityBbox; d: number } | undefined
  for (const city of PRELOAD_CITIES) {
    const cy = (city.bbox[1] + city.bbox[3]) / 2
    const cx = (city.bbox[0] + city.bbox[2]) / 2
    const dy = (lat - cy) * 111
    const dx = (lng - cx) * 111 * Math.cos((lat * Math.PI) / 180)
    const d = Math.hypot(dx, dy)
    if (!best || d < best.d) best = { city, d }
  }
  if (!best) return undefined
  return best.d < 150 ? best.city : undefined
}
