// ============================================================================
// Add-on catalog — the single source of truth for what add-ons exist.
// ----------------------------------------------------------------------------
// New add-on? Add an entry here, ship code that reads it, done. No DB
// migration needed for new add-ons themselves; only their feature-specific
// tables (e.g. provider_qa for the qa add-on) require migrations.
//
// Pricing rules (founder direction 2026-06-07):
// - Free-forever add-ons: priceMonthlyIdr = 0 AND freeForever = true.
//   We never charge for these. They are the hook.
// - Paid add-ons: priceMonthlyIdr > 0. No surprise free trial — show the
//   price prominently from the first card the user sees. Optional explicit
//   trialDays for cases we want to let people try before paying.
// ============================================================================

export type AddonId = 'qa' | 'payments' | 'social-auto'

export type AddonBilling =
  | { kind: 'free-forever' }
  | { kind: 'paid'; priceMonthlyIdr: number; trialDays?: number }

export type Addon = {
  id:           AddonId
  /** Stable internal slug for the URL: /add-ons/<slug>. Matches id today. */
  slug:         string
  /** Lucide icon name. The storefront/dashboard imports this dynamically. */
  iconName:     'MessageCircleQuestion' | 'CreditCard' | 'Sparkles'
  label:        { id: string; en: string }
  /** One-liner that fits on a storefront card under the title. */
  tagline:      { id: string; en: string }
  /** Longer description for the detail page. Markdown-light (plain text + newlines). */
  description:  { id: string; en: string }
  billing:      AddonBilling
  /** Whether v1 is shippable today. Off-flagged add-ons appear on the
   *  storefront in a "Coming soon" state and can't be activated. */
  available:    boolean
}

export const ADDONS: ReadonlyArray<Addon> = [
  {
    id:       'qa',
    slug:     'qa',
    iconName: 'MessageCircleQuestion',
    label: {
      id: 'Tanya & Jawab',
      en: 'Q&A on Profile',
    },
    tagline: {
      id: 'Jawab pertanyaan customer 24 jam tanpa hadir di WhatsApp.',
      en: 'Answer customer questions 24/7 without being on WhatsApp.',
    },
    description: {
      id:
        'Tambahkan daftar pertanyaan & jawaban di profilmu. Customer ' +
        'lihat info penting sebelum chat — kamu tidak perlu jawab ' +
        'pertanyaan yang sama berulang-ulang.\n\n' +
        'Cocok untuk: jam buka, harga paket, area service, syarat ' +
        'booking, cara bayar.',
      en:
        'Add a list of frequently asked questions and answers to your ' +
        'profile. Customers see the key info before they chat — you stop ' +
        'answering the same question over and over.\n\n' +
        'Great for: opening hours, package prices, service area, booking ' +
        'requirements, payment methods.',
    },
    billing:   { kind: 'free-forever' },
    available: true,
  },
  {
    id:       'payments',
    slug:     'payments',
    iconName: 'CreditCard',
    label: {
      id: 'Terima Pembayaran Online',
      en: 'Accept Online Payments',
    },
    tagline: {
      id: 'Customer bayar via Midtrans (QRIS, transfer, kartu). Langsung ke rekening kamu.',
      en: 'Customers pay via Midtrans (QRIS, transfer, card). Goes straight to your bank.',
    },
    description: {
      id:
        'Tombol bayar di profilmu. Customer pilih jasa, bayar di Midtrans ' +
        '(QRIS, bank transfer, atau kartu), uang masuk langsung ke rekening ' +
        'kamu. Kita2u tidak menyimpan dana sama sekali.\n\n' +
        'Cocok untuk: deposit booking, pembayaran penuh, paket prabayar.',
      en:
        'Payment button on your profile. Customer picks a service, pays via ' +
        'Midtrans (QRIS, bank transfer, or card), funds go directly to your ' +
        'bank account. Kita2u never custodies the money.\n\n' +
        'Great for: booking deposits, full payment, prepaid packages.',
    },
    billing:   { kind: 'paid', priceMonthlyIdr: 25_000, trialDays: 14 },
    available: false, // v2 — needs Midtrans per-provider routing
  },
  {
    id:       'social-auto',
    slug:     'social-auto',
    iconName: 'Sparkles',
    label: {
      id: 'Auto Post Sosial Media',
      en: 'Social Auto-Post',
    },
    tagline: {
      id: 'Konten Instagram & TikTok mingguan, dibuat AI dari profilmu.',
      en: 'Weekly Instagram & TikTok captions generated by AI from your profile.',
    },
    description: {
      id:
        'Setiap minggu AI buat 5 caption sosial media untukmu (Instagram, ' +
        'TikTok, Facebook). Berdasarkan layanan, harga, dan foto yang sudah ' +
        'kamu upload. Kamu tinggal copy-paste atau approve untuk auto-post.\n\n' +
        'Cocok untuk: provider yang konsisten ingin posting tapi tidak punya ' +
        'waktu nulis caption sendiri.',
      en:
        'Each week AI generates 5 social media captions for you (Instagram, ' +
        'TikTok, Facebook). Based on the services, prices, and photos you ' +
        'already uploaded. Just copy-paste, or approve for auto-posting.\n\n' +
        'Great for: providers who want to post consistently but don\'t have ' +
        'time to write captions.',
    },
    billing:   { kind: 'paid', priceMonthlyIdr: 35_000, trialDays: 7 },
    available: false, // v2 — needs AI generation pipeline
  },
]

export function findAddon(id: string): Addon | null {
  return ADDONS.find((a) => a.id === id || a.slug === id) ?? null
}

export function formatIdr(n: number): string {
  return 'Rp ' + n.toLocaleString('id-ID')
}

/** Human-friendly price chip text per locale. */
export function priceLabel(addon: Addon, locale: 'id' | 'en'): string {
  if (addon.billing.kind === 'free-forever') {
    return locale === 'id' ? 'Gratis selamanya' : 'Free forever'
  }
  const monthly = formatIdr(addon.billing.priceMonthlyIdr)
  if (locale === 'id') {
    return addon.billing.trialDays
      ? `${monthly} / bulan · Coba gratis ${addon.billing.trialDays} hari`
      : `${monthly} / bulan`
  }
  return addon.billing.trialDays
    ? `${monthly} / month · ${addon.billing.trialDays}-day free trial`
    : `${monthly} / month`
}
