-- ============================================================================
-- 0139 — Short caption + per-platform hashtags on promo_pages
-- ----------------------------------------------------------------------------
-- The original promo_pages.ai_caption is a single 60-180 word body — great
-- for the public landing page, too long for X (280 char limit) or for a
-- Story sticker. Adds:
--
--   ai_caption_short       — 1-sentence punch line ≤200 chars, for X /
--                            Snapchat / story stickers.
--   hashtags_by_platform   — jsonb keyed by platform code; per-platform
--                            tag packs the AI generated alongside the
--                            caption. Empty object when not set.
--                            Shape:
--                              { instagram: ["#tag1","#tag2", ...],
--                                tiktok:    [...],
--                                facebook:  [],
--                                x:         ["#tag1"],
--                                snapchat:  [],
--                                whatsapp:  [] }
--
-- Backfill: existing rows get NULL ai_caption_short + {} hashtags. The
-- share modal degrades gracefully — falls back to the body caption and
-- shows no hashtag block when empty.
-- ============================================================================

alter table public.promo_pages
  add column if not exists ai_caption_short    text,
  add column if not exists hashtags_by_platform jsonb not null default '{}'::jsonb;

comment on column public.promo_pages.ai_caption_short is
  '1-sentence short caption for character-limited platforms (X, Snapchat). '
  '≤200 chars, generated by the AI alongside ai_caption.';

comment on column public.promo_pages.hashtags_by_platform is
  'Per-platform hashtag packs. Keys: instagram, tiktok, facebook, x, '
  'snapchat, whatsapp. Each value is an array of strings including the # '
  'prefix. Empty arrays mean "no hashtags for this platform".';

-- ============================================================================
-- POST-CONDITIONS
--   • Share modal can pick the right caption + hashtag pack per platform.
--   • AI route generates everything in one Claude call via structured JSON.
-- ============================================================================
